### ISSUE TITLE
Exclusive candidate configuration

### ISSUE THREAD

**Issue by krihal** [clicon/clixon-controller#37]
Might be needed for both JunOS, EOS etc.

The controller should use configure private (or configure exclusive?) to make sure that no one else commits the candidate configuration.

**Comment by olofhagsand** [comment]
For junos: 
https://www.juniper.net/documentation/us/en/software/junos/junos-xml-protocol/topics/ref/tag/junos-xml-protocol-open-configuration.html

**Comment by olofhagsand** [comment]
Actually, this changed to "exclusive" access.
The reason is:
(1) private candidate is not a standardized concept
(2) Even in the juniper proprietary solution, private cannot be combined with confirm-commit which is necessary for failures at commit
(3) exclusive is standard using lock/unlock and can be combined with confirm-commit

**Comment by olofhagsand** [comment]
In branch https://github.com/clicon/clixon-controller/tree/exclusive-commit

**Comment by krihal** [comment]
Verified.
